MyProject/MyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from django.conf import settings
from django.conf.urls.static import static
# from django.views.generic import TemplateView


urlpatterns = [
    path('', views.index, name = 'index'),
    path('home/', include('home.urls')),

    path('admin/', admin.site.urls),       #Used for Admin log in

    path('experience/', include('experience.urls')),
    path('signup/', include('registration.urls')), 
    path('portfolio/', include('portfolio.urls')), 
    path('tinymce/', include('tinymce.urls')),
    path('summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyProject/experience/urls.py
from django.urls import path, re_path
from portfolio import views
from .views import ExperienceListView

#Template tagging
app_name = 'experience'

urlpatterns = [
    # path('experience/', views.experience, name="experience"),
    path('experience/', ExperienceListView.as_view(), name='list'),
    ]

MyProject/home/urls.py
from django.urls import path
from home import views


#Template tagging
app_name = 'home'

urlpatterns = [
    path('index/', views.index, name="index"),
    path('about/', views.about, name="about"),   
    path('contact/', views.contact, name="contact"),   
]

MyProject/portfolio/urls.py
from django.urls import path, re_path
from portfolio import views
from .views import PortfolioListView, PortfolioDetailView

#Template tagging
app_name = 'portfolio'

urlpatterns = [
    # path('merger/', views.merger, name="merger"),
    path('portfolio/', PortfolioListView.as_view(), name='list'),
    re_path('(?P<pk>\d+)/', views.PortfolioDetailView.as_view(), name='detail'),
]

MyProject/experience/models.py
from django.db import models
from django.http import HttpResponseRedirect
from django.shortcuts import render


class Experience(models.Model):

    SECTIONS = (
        (" ", " "),
        ("WORK EXPERIENCE", "WORK EXPERIENCE"),
        ("EDUCATION", "EDUCATION"),
        ("SKILLS", "SKILLS"),
    )

    experience_section = models.CharField(max_length = 50, choices = SECTIONS, default = "", blank=True)
    experience_company = models.CharField(max_length = 100, default = "", blank=True)
    date_from = models.CharField(max_length = 50, blank=True)
    date_to = models.CharField(max_length = 50, blank=True)
    experience_content = models.TextField(blank=True)
    experience_published = models.DateTimeField("date_published", auto_now_add=True, blank=True)
    experience_job_title = models.CharField(max_length = 200, blank=True)
    experience_order = models.CharField(max_length = 3, default = "0", blank=True)

    class Meta:
       ordering = ['experience_order']

    def __str__(self):
        return self.experience_job_title

    def get_absolute_url(self):
        return reverse("experience:detail",kwargs={'pk':self.pk})

MyProject/home/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.

# class Topic(models.Model):
#     top_name = models.CharField(max_length = 264, unique = True)

#     def __str__(self):
#         return self.top_name


# class Webpage(models.Model):
#     topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
#     name = models.CharField(max_length = 264, unique = True)
#     url = models.URLField(unique = True)

#     def __str__(self):
#         return self.name


# class AccessRecord(models.Model):
#     name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
#     date = models.DateField()

#     def __str__(self):
#         return str(self.date)


# class School(models.Model):
#     name = models.CharField(max_length = 256)
#     principal = models.CharField(max_length = 256)
#     location = models.CharField(max_length = 256)

#     def __str__(self):
#         return self.name

# class Student(models.Model):
#     name = models.CharField(max_length = 256)
#     age = models.PositiveIntegerField()
#     school = models.ForeignKey(School, related_name = 'students', on_delete = models.CASCADE)

#     def __str__(self):
#         return self.name

MyProject/portfolio/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from PIL import Image

# Create your models here.

# class Post(models.Model):
#     author = models.ForeignKey('auth.User', on_delete = models.CASCADE)
#     title = models.CharField(max_length = 200)
#     text = models.TextField()
#     create_date = models.DateTimeField(default = timezone.now())
#     published_date = models.DateTimeField(blank = True, null = True)

#     def publish(self):
#         self.published_date = timezone.now()
#         self.save()

#     def approve_comments(self):
#         return self.comments.filter(approved_comment = True)

#     def get_absolute_url(self):
#         return reverse('post_detail', kwargs = {'pk':self.pk})

#     def __str__(self):
#         return self.title

# class Comment(models.Model):
#     post = models.ForeignKey('portfolio.Post', related_name = 'comments', on_delete = models.CASCADE)
#     author = models.CharField(max_length = 200)
#     text = models.TextField()
#     create_date = models.DateTimeField(default = timezone.now())
#     approved_comment = models.BooleanField(default = False)

#     def approve(self):
#         self.approved_comment = True
#         self.save()

#     def get_absolute_url(self):
#         return reverse('post_list')

#     def __str__(self):
#         return self.text

class Project(models.Model):
    project_title = models.CharField(max_length = 50)
    project_short_summary = models.CharField(max_length = 100, default = "Short summary")
    project_summary = models.TextField()
    project_content = models.TextField()
    project_published = models.DateTimeField("date_published", auto_now_add=True, blank=True)
    project_author = models.CharField(max_length = 200, default = "No author")
    project_github = models.CharField(max_length = 255, default = "No link")
    project_image = models.ImageField(default = "notfound.jpg", upload_to='portfolio_logo')

    class Meta:
        ordering = ['-project_published']

    # def save(self):
    #     super().save()  # saving image first

    #     img = Image.open(self.project_image.path) # Open image using self

    #     if img.height > 1024 or img.width > 1024:
    #         new_img = (1024, 1024)
    #         img.thumbnail(new_img)
    #         img.save(self.project_image.path)  # saving image at the same path

    def __str__(self):
        return self.project_title

    def get_absolute_url(self):
        return reverse("portfolio:detail",kwargs={'pk':self.pk})

MyProject/experience/forms.py
from django import forms

MyProject/home/forms.py
from django import forms
from django.core import validators

MyProject/portfolio/forms.py
from django import forms

# from portfolio.models import Post, Comment

# class PostForm(forms.ModelForm):
#     class Meta():
#         model = Post
#         fields = ('author', 'title', 'text')

#         widgets = {
#             'title':forms.TextInput(attrs = {'class':'textinputclass'})
#             'text':forms.Textarea(attrs = {'class':'editable medium-editor-textarea postcontent'})
#         }

# class CommentForm(forms.ModelForm):
#     class Meta():
#         model = Comment
#         fields = ('author', 'text')

#         widgets = {
#             'author':forms.TextInput(attrs = {'class':'textinputclass'})
#             'text':forms.Textarea(attrs = {'class':'editable medium-editor-textarea'})
#         }

MyProject/experience/views.py
from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponse, HttpRequest
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)
from .models import Experience
from . import models


# def experience(request):
#     return render(request, "experience.html")

class ExperienceListView(ListView):
    context_object_name = 'experience'
    model = models.Experience

MyProject/home/views.py
from django.shortcuts import render
from home import forms
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import View, TemplateView, ListView, DetailView
from . import models

def index(request):
    return render(request, "index.html")

def about(request):
    return render(request, "about.html")

def contact(request):
    return render(request, "contact.html")



# class IndexView(TemplateView):
#     template_name = 'templates/index.html'

# class AboutView(TemplateView):
#     template_name = 'about.html'


    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['injectme'] = 'BASIC INJECTION!'
    #     return context


# class SchoolListView(ListView):
#     context_object_name = 'schools'
#     model = models.School


# class SchoolDetailView(DetailView):
#     context_object_name = 'school_detail'
#     model = models.School
#     template_name = 'home/school_detail.html'

MyProject/portfolio/views.py
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse, HttpRequest
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)
from .models import Project
from . import models

# def portfolio(request):
#     return render(request = request,
#                   template_name='portfolio.html',
#                   context = {"project":Project.objects.all})


class PortfolioListView(ListView):
    context_object_name = 'project'
    model = models.Project

class PortfolioDetailView(DetailView):
    context_object_name = 'project_details'
    model = models.Project
    template_name = 'portfolio/project_detail.html'


def model_form_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = DocumentForm()
    return render(request, 'core/merger.html', {
        'form': form
    })

MyProject/templates/base/base.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
{% load static %}
{% include 'base/message.html' %}
  <head>
    <!-- <script src="{% static 'js/script.js' %}"></script> -->
    <script src="{% static 'js/nodes.js' %}"></script>
    <link rel="shortcut icon" href="{% static 'images/favicon.svg' %}">
    <meta charset="utf-8">
    <title>Karolis Kimtys | Web Developer</title>

    <link rel="stylesheet" href="/static/css/mystyle.css">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
    crossorigin="anonymous">

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" 
    crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
 
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=no,user-scalable=0"/>

    <title>nodes.js - js connected nodes animation</title>
    <meta name="description" content="nodes.js is a nodes/particles animation useable for backgrounds">
    <meta name="keywords" content="nodes, animation, particlees, web, html5, canvas, backgorund">

  </head>

    <!-- <script>
      $(function(){
          $('a').each(function(){
              if ($(this).prop('href') == window.location.href) {
                  $(this).addClass('active'); $(this).parents('li').addClass('active');
              }
          });
      });
    </script> -->

    <!-- <nodes.js embedding> -->
  <script type="text/javascript" src="{% static 'js/nodes.js' %}"></script>
  <script type="text/javascript">
            var nodesjs = new NodesJs({
                id: 'nodes',
                width: window.innerWidth,
                height: window.innerHeight,
                particleSize: 1,
                lineSize: 0.5,
                particleColor: [255, 255, 255, 0.3],
                lineColor: [255, 255, 255],
                backgroundFrom: [10, 25, 100],
                backgroundTo: [25, 50, 150],
                backgroundDuration: 4000,
                nobg: true,
                number: window.hasOwnProperty('orientation') ? 30: 100,
                speed: 10
            });
        </script>
        <div style="position: fixed;
                  left: 0px; 
                  top: 0px; 
                  overflow: hidden;
                  width: 100%; 
                  height: 100%;
                  z-index: -5;">
            <canvas id="nodes"></canvas>
        </div>
        <!-- </nodes.js embedding> -->

        <script type="text/javascript">
            window.onresize = function () {
                nodesjs.setWidth(window.innerWidth);
                nodesjs.setHeight(window.innerHeight);
            };
    </script>

    <script>
        function fadeInPage() {
          if (!window.AnimationEvent) { return; }
          var fader = document.getElementById('fader');
          fader.classList.add('fade-out');
      }
    </script> 

    <script>
        document.addEventListener('DOMContentLoaded', function() {
        if (!window.AnimationEvent) { return; }
        var anchors = document.getElementsByTagName('a');
        for (var idx=0; idx<anchors.length; idx+=1) {
          if (anchors[idx].hostname !== window.location.hostname ||
            anchors[idx].pathname === window.location.pathname) {
            continue;
        }
        anchors[idx].addEventListener('click', function(event) {
            var fader = document.getElementById('fader'),
                anchor = event.currentTarget;
            
            var listener = function() {
                window.location = anchor.href;
                fader.removeEventListener('animationend', listener);
            };
            fader.addEventListener('animationend', listener);
            
            event.preventDefault();
            fader.classList.add('fade-in');
                });
            }
        });
        window.addEventListener('pageshow', function (event) {
          if (!event.persisted) {
            return;
          }
          var fader = document.getElementById('fader');
          fader.classList.remove('fade-in');
        });
    </script>

    <script>
      $(document).ready(function () {
          $(document).click(function (event) {
              var clickover = $(event.target);
              var _opened = $(".navbar-collapse").hasClass("navbar-collapse in");
              if (_opened === true && !clickover.hasClass("navbar-toggler")) {
                  $("button.navbar-toggler").click();
              }
          });
      });
    </script>

    <script>
      $(function() {
        $(document).click(function (event) {
          $('.navbar-collapse').collapse('hide');
        });
      });
    </script>

    <script>
      $(function(){
          $('a').each(function(){
              if ($(this).prop('href') == window.location.href) {
                  $(this).addClass('active'); $(this).parents('li').addClass('active');
              }
          });
      });
    </script>

<style>  

  body{
  background-image: url("{% static 'images/mount.jpg' %}");
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center center;
  background-attachment: fixed;
  background-color: rgb(0, 0, 0);
  z-index: 1000;
  }

</style>

  <!-- <video autoplay muted loop id="myVideo">
    <source src="{% static 'images/rain.mp4' %}" type="video/mp4">
    <script>document.querySelector('video').playbackRate = 0.75;</script>
  </video> -->

<body>

    <svg id="fader"></svg>
    <script>
      fadeInPage();
    </script>

    <nav class="sidebar">
      <button id = "menubtn" class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <img class = "social" src="{% static 'images/menu.svg' %}" alt="">MENU</button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <ul class="nav navbar-nav">
          <div class="linkicons">
            <li>
              <a id="navbtn" class="nav-link active" href="{% url 'index' %}">
                <img class = "social" src="{% static 'images/home.svg' %}" alt="">Home</a>
            </li>
            <li>
              <a id="navbtn" class="nav-link active" href="{% url 'portfolio:list' %}">
                <img class = "social" src="{% static 'images/portfolio.svg' %}" alt="">Portfolio</a>
              </a>
            </li>
            <li>
              <a id="navbtn" class="nav-link active" href="{% url 'experience:list' %}">
                <img class = "social" src="{% static 'images/resume.svg' %}" alt="">Experience</a>
              </a>
            </li>
            <li>
              <a id="navbtn" class="nav-link active" href="{% url 'home:about' %}">
                <img class = "social" src="{% static 'images/contact.svg' %}" alt="">About</a>
              </a>
            </li>
            <li>
              <a id="navbtn" class="nav-link active" href="{% url 'home:contact' %}">
                <img class = "social" src="{% static 'images/about.svg' %}" alt="">Contact</a>
              </a>
            </li>
              <a id="navbtn" class="nav-link active" href="{% url 'admin:index' %}">
                <img class = "social" src="{% static 'images/admin.svg' %}" alt="">Admin</a>
              </a>
          </div>

        </ul>
        </div>
    </nav>



    {% block body_block %}
    {% endblock %}
    
</body>
</html>

MyProject/templates/base/message.html
{% load static %}
{% for message in messages %}
  <div class="toast notification bg-dark" role="alert" aria-live="assertive" aria-atomic="true" data-delay="5000">
    <div class="toast-header">
      <img src="{% static "images/favicon.png" %}" width="20" height="20" class="rounded mr-2" alt="...">
      <strong class="mr-auto">
        {% if message.tags == 'error' %}
          <i class="fas fa-times mr-2"></i>
        {% elif message.tags == 'warning' %}
          <i class="fas fa-exclamation mr-2"></i>
        {% elif message.tags == 'info' %}
          <i class="fas fa-info mr-2"></i>
        {% elif message.tags == 'success' %}
          <i class="fas fa-check mr-2"></i>
        {% endif %}
        {{message.tags|capfirst}}
      </strong>
    </div>
    <div class="toast-body">
      {{message|safe}}
    </div>
  </div>
{% endfor %}